apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: trusted-artifact-signer
  finalizers:
    - client.cleanup
  labels:
    app: sso
spec:
  client:
    clientAuthenticatorType: client-secret
    redirectUris:
      - '*'
    serviceAccountsEnabled: true
    clientId: trusted-artifact-signer
    defaultClientScopes:
      - profile
      - email
    name: trusted-artifact-signer
    implicitFlowEnabled: false
    publicClient: false
    standardFlowEnabled: true
    attributes:
      request.object.signature.alg: RS256
      user.info.response.signature.alg: RS256
    protocol: openid-connect
    protocolMappers:
      - config:
          claim.name: email
          id.token.claim: 'true'
          jsonType.label: String
          user.attribute: email
          userinfo.token.claim: 'true'
        name: email
        protocol: openid-connect
        protocolMapper: oidc-usermodel-property-mapper
      - config:
          claim.name: email-verified
          id.token.claim: 'true'
          user.attribute: emailVerified
          userinfo.token.claim: 'true'
        name: email-verified
        protocol: openid-connect
        protocolMapper: oidc-usermodel-property-mapper
      - config:
          access.token.claim: 'true'
          claim.name: aud
          claim.value: trusted-artifact-signer
          id.token.claim: 'true'
          userinfo.token.claim: 'true'
        name: audience
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
    id: 5d1c1c9f-da73-4ed9-a0ea-de6c7a006f42
    description: Client for Red Hat Trusted Artifact Signer authentication
    directAccessGrantsEnabled: true
  realmSelector:
    matchLabels:
      app: sso
  scopeMappings: {}