kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: crc-csi-hostpath-provisioner
  volumeMode: Filesystem