kind: Secret
apiVersion: v1
metadata:
  name: keyless-signing-info
stringData:
  CLIENT_ID: trusted-artifact-signer
  CLIENT_SECRET: <ADD_SECRET_HERE>
  PASSWORD: secure
  USER: jdoe@redhat.com
type: Opaque
