apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sign-image
spec:
  workspaces:
    - name: ca-cert
      mountPath: /etc/pki/tls/certs/
  steps:
    - image: 'image-registry.openshift-image-registry.svc:5000/cicd/rhtas-cosign-rhel9:1.0.1-1716203248'
      name: sign
      env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keyless-signing-info
              key: CLIENT_SECRET
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: keyless-signing-info
              key: CLIENT_ID
        - name: SIGNER
          valueFrom:
            secretKeyRef:
              name: keyless-signing-info
              key: USER
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: keyless-signing-info
              key: PASSWORD
      script: |
        echo "Initializing..."

        export TUF_URL="https://tuf-trusted-artifact-signer.apps-crc.testing"
        export OIDC_ISSUER_URL="https://keycloak-sso.apps-crc.testing/auth/realms/trusted-artifact-signer"
        export COSIGN_FULCIO_URL="https://fulcio-server-trusted-artifact-signer.apps-crc.testing"
        export COSIGN_REKOR_URL="https://rekor-server-trusted-artifact-signer.apps-crc.testing"
        export COSIGN_MIRROR="https://tuf-trusted-artifact-signer.apps-crc.testing"
        export COSIGN_ROOT="https://tuf-trusted-artifact-signer.apps-crc.testing/root.json"
        export COSIGN_OIDC_CLIENT_ID="trusted-artifact-signer"
        export COSIGN_OIDC_ISSUER="https://keycloak-sso.apps-crc.testing/auth/realms/trusted-artifact-signer"
        export COSIGN_CERTIFICATE_OIDC_ISSUER="https://keycloak-sso.apps-crc.testing/auth/realms/trusted-artifact-signer"
        export COSIGN_YES="true"
        export SIGSTORE_FULCIO_URL="https://fulcio-server-trusted-artifact-signer.apps-crc.testing"
        export SIGSTORE_OIDC_ISSUER="https://keycloak-sso.apps-crc.testing/auth/realms/trusted-artifact-signer"
        export SIGSTORE_REKOR_URL="https://rekor-server-trusted-artifact-signer.apps-crc.testing"
        export REKOR_REKOR_SERVER="https://rekor-server-trusted-artifact-signer.apps-crc.testing"

        cosign initialize

        echo "Obtaining OIDC token..."

        export KEYCLOAK_URL=$OIDC_ISSUER_URL/protocol/openid-connect/token

        RESPONSE=$(curl -v -k -X POST "$KEYCLOAK_URL" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=password" \
          -d "client_id=$CLIENT_ID" \
          -d "client_secret=$CLIENT_SECRET" \
          -d "username=$SIGNER" \
          -d "password=$PASS")

        TOKEN=$(echo $RESPONSE | grep -o '"access_token":"[^"]*' | awk -F'"' '{print $4}')
        
        echo "Signing..."
        export SIGSTORE_ID_TOKEN=$TOKEN
        cosign sign -y quay.io/jpmaida1/ping-pong:latest
