apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: 'true'
    pipeline.openshift.io/started-by: kubeadmin
  generateName: pipeline-build-and-sign-image-
  finalizers:
    - chains.tekton.dev/pipelinerun
  labels:
    tekton.dev/pipeline: pipeline-build-and-sign-image
spec:
  params:
    - name: TAG_TO_BE_DEPLOYED
      value: '1.0'
  pipelineRef:
    name: pipeline-build-and-sign-image
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: shared-ws
      persistentVolumeClaim:
        claimName: shared-ws-pvc
    - name: ca-cert
      configMap:
        name: config-registry-cert
    - name: images-url
      emptyDir: {}