kind: Secret
apiVersion: v1
metadata:
  name: quay-creds
  annotations:
    tekton.dev/docker-0: 'https://quay.io'
stringData:
  password: "<password>"
  username: "<username>"
type: kubernetes.io/basic-auth
