kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: trivy-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: crc-csi-hostpath-provisioner
  volumeMode: Filesystem